### ISSUE TITLE
WARNING: Makefile 'package/lean/luci-app-passwall/Makefile' 

### ISSUE THREAD

**Issue by jikuohong** [hong0980/luci-app-passwall#2]
WARNING: Makefile 'package/lean/luci-app-passwall/Makefile' has a dependency on 'tcping', which does not exist
WARNING: Makefile 'package/lean/luci-app-passwall/Makefile' has a dependency on 'brook', which does not exist
WARNING: Makefile 'package/lean/luci-app-passwall/Makefile' has a dependency on 'chinadns-ng', which does not exist
WARNING: Makefile 'package/lean/luci-app-passwall/Makefile' has a dependency on 'dns2socks', which does not exist

**Comment by hong0980** [comment]
https://github.com/Lienol/openwrt-package/tree/6ba52eb68777314baf203e747140fb83b1899d20/package 安装这个依赖
