### ISSUE TITLE
这个插件如何安装？

### ISSUE THREAD

**Issue by zhangsean** [hong0980/luci-app-passwall#3]
看到Actions里这个插件是独立编译的，构建产物是.tar.gz，不是.ipk格式，这个插件要如何安装？
另外这个插件和 Lienol 的passwall有什么不一样吗？
O(∩_∩)O谢谢！

**Comment by hong0980** [comment]
解压出来一样的，是原来安装过后覆盖安装更新用。

**Comment by hong0980** [comment]
> 看到Actions里这个插件是独立编译的，构建产物是.tar.gz，不是.ipk格式，这个插件要如何安装？
> 另外这个插件和 Lienol 的passwall有什么不一样吗？
> O(∩_∩)O谢谢！

解压出来一样的，是原来安装过后覆盖安装更新用。

**Comment by zhangsean** [comment]
解压出来就是.ipk文件，谢谢！
