### ISSUE TITLE
大神passwall需要依赖么？我这样写对么？

### ISSUE THREAD

**Issue by zh610902551** [hong0980/luci-app-passwall#5]
name: Clone passwall code
run: |
   cd openwrt-package
   mkdir packages
   cd openwrt-packages
   git clone https://github.com/hong0980/luci-app-passwall.git 
# 常用LuCI插件选择:
           cat >> .config <<EOF
            CONFIG_PACKAGE_lluci-app-passwall=y

**Comment by hong0980** [comment]
我的库没有依赖，需要下面的依赖DEPENDS:=+libmbedtls +iptables-mod-tproxy +kmod-ipt-tproxy +iptables-mod-ipopt +kmod-ipt-ipopt +ip +ipset +coreutils +coreutils-base64 +coreutils-nohup +luci-lib-jsonc ，你去拉取Lienol大神的源码。https://github.com/Lienol/openwrt-package，云编译建议加.config文件。
